module.exports = {
    "CZ 3002":[
        {question:"Which is NOT a classic software development mistake?",answers:["People-Related","Language-Related","Process-Related","Product-Related","Tech-Related"],ans:1},
        {question:"What is the difference in Productivity among individuals with the same levels of experience?",answers:["8-to-1","5-to-1","10-to-1","2.5-to-1"],ans:2},
        {question:"Which is NOT a Tech-Related mistakes?",answers:["Lack of automated source-code control","Silver-bullet syndrome","Overestimated savings from new tools or methods","Requirements gold-plating"],ans:3},
        {question:"Which is a Product-Related mistakes?",answers:["Feature creep","Planning to catch up later","Code-like hell programming","Inadequate design"],ans:0},
        {question:"Which is NOT mentioned in the McCall's Quality Model?",answers:["Human operations","Product Revision","Product Operations","Product Transition"],ans:0},
        {question:"Which is NOT a characteristic of the ISO 9126 Quality Model",answers:["Functionality","Reliabilty","Efficiency","Review Frequently"],ans:3},
        {question:"Cause and effect diagrams trace complaints about quality problems back to the responsible production operations. Which of the following is another name for this diagaram?",answers:["Effect and Cause","FishBone","Dogbone","Tree diagram"],ans:1},
        {question:"What does the M in DMAIC stand for",answers:["Match","Measure","Maintain","Map"],ans:1},
        {question:"Which is NOT a quality management activity?",answers:["Quality Assurance","Quality Planning","Quality Control","Quality Measurement"],ans:3},
        {question:"Which is NOT a category for cost relating to quality",answers:["Specification Cost","Appraisal Cost","Internal Failure Cost","External Failure Cost", "Prevention Cost", "None of the above"],ans:0},
    ],
    "CZ 2001":[
        {question:"Placeholder question 1",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 2",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 3",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 4",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 5",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 6",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 7",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 8",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 9",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 10",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},

    ],
    "CZ 1001":[
        {question:"Placeholder question 1",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 2",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 3",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 4",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 5",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 6",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 7",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 8",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 9",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 10",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
    ],
    "CZ 1002":[
        {question:"Placeholder question 1",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 2",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 3",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 4",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 5",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 6",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 7",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 8",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 9",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 10",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
    ],
    "CZ 1003":[
        {question:"Placeholder question 1",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 2",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 3",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 4",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 5",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 6",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 7",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 8",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 9",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
        {question:"Placeholder question 10",answers:["Ans1","Ans2","Ans3","Ans4"],ans:1},
    ],
};